config/routes.rb
Monologue::Engine.routes.draw do
  root to:  "posts#index"
  get "/page/:page", to:  "posts#index", as:  "posts_page"
  get "/feed" => "posts#feed", as:  "feed", defaults: {format: :rss}

  get "/tags/:tag" =>"tags#show", as: "tags_page"

  namespace :admin, path: "monologue" do
    get "/" => "posts#index", as:  "" # responds to admin_url and admin_path
    get "/page/:page", to:  "posts#index", as:  "posts_page"
    get "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    resources :sessions
    resources :posts
    resources :users
    get "comments" => "comments#show", as: "comments"

    match "/post/preview"=>"posts#preview", :as=>"post_preview", :via => [:put, :post]
  end

  get "*post_url" => "posts#show", as:  "post"
end

app/models/monologue/user.rb
class Monologue::User < ActiveRecord::Base
  has_many :posts

  has_secure_password

  validates_presence_of :password, on: :create
  validates_presence_of :name
  validates :email , presence: true, uniqueness: true


  def can_delete?(user)
    return false if self==user
    return false if user.posts.any?
    true
  end
end

app/controllers/monologue/admin/users_controller.rb
class Monologue::Admin::UsersController < Monologue::Admin::BaseController

  before_filter :load_user, except: [:index, :new, :create]

  def edit

  end

  def new
    @user = Monologue::User.new
  end

  def update
    if @user.update user_params
      flash.notice = "User modified"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice:  I18n.t("monologue.admin.users.delete.removed", user: @user.name)
    else
      redirect_to admin_users_path, alert: I18n.t("monologue.admin.users.delete.failed", user: @user.name)
   end
  end

  def create
    @user = Monologue::User.new user_params
    if @user.save
      flash.notice = I18n.t("monologue.admin.users.create.success")
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def index
    @users = Monologue::User.all
  end

  private
    def load_user
      @user = Monologue::User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/controllers/monologue/controller_helpers/user.rb
require 'active_support/concern'

module Monologue
  module ControllerHelpers
    module User
      extend ActiveSupport::Concern

      included do
        helper_method :monologue_current_user
      end

      private
      def monologue_current_user
        @monologue_current_user ||= Monologue::User.find(session[:monologue_user_id]) if session[:monologue_user_id]
      end
    end
  end
end

app/views/monologue/admin/users/_form.html.erb
<%= user.error_messages %>
<%= user.text_field :name, label:  t(".name"), class:  "span6" %>
<%= user.text_field :email, label:  t(".email"), class:  "span6" %>
<%= user.password_field :password, label:  t(".password"), class:  "span6" %>
<%= user.password_field :password_confirmation, label:  t(".password_confirmation"), class:  "span6" %>

app/views/monologue/admin/users/edit.html.erb
<h1><%= t(".header") %></h1>
<%= monologue_admin_form_for [:admin, @user], method: :put do |user| %>
  <%= render :partial => 'form', :locals => { :user => user } %>
  <%= user.submit t(".save"), class:  "btn btn-large btn-primary" %>
<% end %>

app/views/monologue/admin/users/index.html.erb
<h2><%= link_to t(".create"), new_admin_user_path, class: "btn btn-success" %></h2>

<table class="table table-striped table-bordered">
  <thead>
  <tr>
    <th><%= t(".name") %></th>
    <th><%= t(".email") %></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= link_to t(".edit"), edit_admin_user_path(user), class: "btn btn-small" %></td>
      <td>
        <% if monologue_current_user.can_delete?(user) %>
          <%= link_to t(".delete"), [:admin, user], data: { confirm: 'Are you sure?' }, method: :delete, class: "btn btn-small btn-danger" %>
        <% else %>
          <a href="#" class="btn btn-small btn-danger disabled"><%= t(".delete") %></a>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/monologue/admin/users/new.html.erb
<h1><%= t(".header") %></h1>
<%= monologue_admin_form_for [:admin, @user], method: :post do |user| %>
  <%= render :partial => 'form', :locals => { :user => user } %>
  <%= user.submit t(".create"), class:  "btn btn-large btn-primary" %>
<% end %>