config/routes.rb
Monologue::Engine.routes.draw do
  root to:  "posts#index"
  get "/page/:page", to:  "posts#index", as:  "posts_page"
  get "/feed" => "posts#feed", as:  "feed", defaults: {format: :rss}

  get "/tags/:tag" =>"tags#show", as: "tags_page"

  namespace :admin, path: "monologue" do
    get "/" => "posts#index", as:  "" # responds to admin_url and admin_path
    get "/page/:page", to:  "posts#index", as:  "posts_page"
    get "logout" => "sessions#destroy"
    get "login" => "sessions#new"
    resources :sessions
    resources :posts
    resources :users
    get "comments" => "comments#show", as: "comments"

    match "/post/preview"=>"posts#preview", :as=>"post_preview", :via => [:put, :post]
  end

  get "*post_url" => "posts#show", as:  "post"
end

app/models/monologue/post.rb
class Monologue::Post < ActiveRecord::Base
  # has_many :taggings
  # has_many :tags, -> { order "id ASC" }, through: :taggings, dependent: :destroy
  before_validation :generate_url
  belongs_to :user

  scope :default,  -> {order("published_at DESC, monologue_posts.created_at DESC, monologue_posts.updated_at DESC") }
  scope :published, -> { default.where(published: true).where("published_at <= ?", DateTime.now) }

  # default_scope{includes(:tags)}

  validates :user_id, presence: true
  validates :title, :content, :url, :published_at, presence: true
  validates :url, uniqueness: true
  validate :url_do_not_start_with_slash

  def tag_list= tags_attr
    self.tag!(tags_attr.split(","))
  end

  def tag_list
    self.tags.map { |tag| tag.name }.join(", ") if self.tags
  end

  def tag!(tags_attr)
    self.tags = tags_attr.map(&:strip).reject(&:blank?).map do |tag|
      Monologue::Tag.where(name: tag).first_or_create
    end
  end

  def full_url
    "#{Monologue::Engine.routes.url_helpers.root_path}#{self.url}"
  end

  def published_in_future?
    self.published && self.published_at > DateTime.now
  end

  def self.page p
    paged_results(p, Monologue::Config.posts_per_page || 10, false)
  end

  def self.listing_page(p)
    paged_results(p, Monologue::Config.admin_posts_per_page || 50, true)
  end

  def self.total_pages
    @number_of_pages
  end

  def self.set_total_pages per_page
    @number_of_pages = self.count / per_page + (self.count % per_page == 0 ? 0 : 1)
  end

  private

  def self.paged_results(p, per_page, admin)
    set_total_pages(per_page)
    p = (p.nil? ? 0 : p.to_i - 1)
    offset =  p * per_page
    if admin
      default.limit(per_page).offset(offset)
    else
      limit(per_page).offset(offset)
    end
  end

  def generate_url
    return unless self.url.blank?
    year = self.published_at.class == ActiveSupport::TimeWithZone ? self.published_at.year : DateTime.now.year
    self.url = "#{year}/#{self.title.parameterize}"
  end

  def url_do_not_start_with_slash
    errors.add(:url, I18n.t("activerecord.errors.models.monologue/post.attributes.url.start_with_slash")) if self.url.start_with?("/")
  end
end

app/controllers/monologue/admin/posts_controller.rb
class Monologue::Admin::PostsController < Monologue::Admin::BaseController
  respond_to :html
  before_filter :load_post, only: [:edit, :update]
  
  def index
    @page = params[:page].nil? ? 1 : params[:page]
    @posts = Monologue::Post.listing_page(@page).includes(:user)
  end

  def new
    @post = Monologue::Post.new
  end

  ## Preview a post without saving.
  def preview
    # mockup our models for preview.
    @post = Monologue::Post.new post_params
    @post.user_id = monologue_current_user.id
    @post.published_at = Time.zone.now
    # render it exactly as it would display when live.
    render "/monologue/posts/show", layout: Monologue::Config.layout || "/layouts/monologue/application"
  end

  def create
    @post = Monologue::Post.new post_params
    @post.user_id = monologue_current_user.id
    if @post.save
      prepare_flash_and_redirect_to_edit()
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      prepare_flash_and_redirect_to_edit()
    else
      render :edit
    end
  end

  def destroy
    post = Monologue::Post.find(params[:id])
    if post.destroy
      redirect_to admin_posts_path, notice:  I18n.t("monologue.admin.posts.delete.removed")
    else
      redirect_to admin_posts_path, alert: I18n.t("monologue.admin.posts.delete.failed")
    end
  end

private
  def load_post
    @post = Monologue::Post.find(params[:id])
  end

  def prepare_flash_and_redirect_to_edit
    if @post.published_in_future? && ActionController::Base.perform_caching
      flash[:warning] = I18n.t("monologue.admin.posts.#{params[:action]}.saved_with_future_date_and_cache")
    else
      flash[:notice] =  I18n.t("monologue.admin.posts.#{params[:action]}.saved")
    end
    redirect_to edit_admin_post_path(@post)
  end

  def post_params
    params.require(:post).permit(:published, :tag_list,:title,:content,:url,:published_at)
  end
end

app/controllers/monologue/posts_controller.rb
class Monologue::PostsController < Monologue::ApplicationController
  def index
    @page = params[:page].nil? ? 1 : params[:page]
    @posts = Monologue::Post.page(@page).includes(:user).published
  end

  def show
    if monologue_current_user
      @post = Monologue::Post.default.where("url = :url", {url: params[:post_url]}).first
    else
      @post = Monologue::Post.published.where("url = :url", {url: params[:post_url]}).first
    end
    if @post.nil?
      not_found
    end
  end

  def feed
    @posts = Monologue::Post.published.limit(25)
    # if params[:tags].present?
    #   tags = Monologue::Tag.where(name: params[:tags].split(",")).pluck(:id)
    #   @posts = @posts.joins(:taggings).where("monologue_taggings.tag_id in (?)", tags)
    # end
    render 'feed', layout: false
  end
end

app/views/monologue/admin/posts/_form.html.erb
<%= post.error_messages %>
<%= post.text_field :title, label:  t(".title"), class:  "span6" %>
<%= post.text_area :content, label:  t(".content"), class:  "span12 ckeditor", id: "post_content" %>
<%= post.text_field :url, label:  raw(t(".url.caption", default_url: "#{DateTime.now.year}/#{t(".url.generated_title")}", root: monologue.root_path)) %>
<%= post.text_field :published_at, label:  t(".published_at"), data: {datepicker: "datepicker"}, value: post.object.published_at.nil? ? "" : post.object.published_at.strftime("%Y-%m-%d") %>
<%= post.text_field :tag_list, label:  raw(t(".tags")) %>
<%= post.check_box :published, label:  t(".published") %>

<div class="form-actions">
  <%= post.button t(".save"), class:  "btn btn-large btn-primary" %> 
  <%= post.button t(".preview"), class: "btn btn-large", type: "button", value: "preview"%>
</div>

<div class="post-preview modal-backdrop hide" data-url="<%=admin_post_preview_url%>" data-toggle="post-preview" data-trigger="button[value='preview']">
  <div class="post-preview-inner">
    <div class="navbar pull-right">
      <div class="navbar-inner">
        <span class="brand"><%=t(".preview")%></span> 
        <a class="btn btn-primary pull-right" data-dismiss="post-preview"><%=t(".close")%></a>
      </div>
    </div>
  </div>
  <iframe src="" name="preview"></iframe>
</div>

<script>
  if($.fn.datepicker.defaults_<%= I18n.locale %>){
    $.fn.datepicker.defaults = $.fn.datepicker.defaults_<%= I18n.locale %>;
  }
  $("#post_tag_list").select2({tags: <%= Monologue::Tag.all.map{|t| t.name }.to_json.html_safe %> });
</script>

app/views/monologue/admin/posts/_pagination.html.erb
<div id="pagination">
  <% if @posts.total_pages > 1 && @posts.total_pages != @page.to_i %>
    <%= link_to t(".older_posts"), admin_posts_page_path(@page.to_i+1), class: "older_posts" %>
  <% end %>

  <% if @posts.total_pages > 1 && @page.to_i > 1 %>
    <%= link_to t(".newer_posts"), admin_posts_page_path(@page.to_i-1), class: "newer_posts" %>
  <% end %>
</div>

app/views/monologue/admin/posts/edit.html.erb
<h1><%= t(".header") %> "<%= @post.title %>"</h1>
<%= monologue_admin_form_for ["admin", @post], method: :put do |post| %>
  <%= render partial: 'form', locals: {post: post} %>
<% end %>

app/views/monologue/admin/posts/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= t(".title")%></th>
      <th><%= t(".status")%></th>
      <th><%= t(".author")%></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post|%>
      <tr>
        <td><%= link_to post.title, edit_admin_post_path(post) %></td>
        <td><span class="label label-<%= post.published ? "success" : "important" %>"><%= post.published ? t(".published") : t(".not_published") %></span></td>
        <td><span><%= post.user.name %></span> </td>
        <td><%= link_to t(".edit"), edit_admin_post_path(post), class: "btn btn-small" %></td>
        <td><%= link_to t(".delete"), [:admin, post],data: {confirm: 'Are you sure?'}, method: :delete, class: "btn btn-small btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if @page %>
  <%= render partial: "pagination" %>
<% end %>

app/views/monologue/admin/posts/new.html.erb
<h1><%= t(".header") %></h1>
<%= monologue_admin_form_for ["admin", @post] do |post| %>
  <%= render partial: 'form', locals: {post: post} %>
<% end %>